"""initial schema

Revision ID: 935f5ab19963
Revises:
Create Date: 2026-03-03 17:34:25.164963
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "935f5ab19963"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ohlcv",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("exchange", sa.String(length=30), nullable=False),
        sa.Column("timeframe", sa.String(length=5), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("volume", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "exchange", "timeframe", "timestamp", name="uq_ohlcv_candle"),
    )
    op.create_index(op.f("ix_ohlcv_symbol"), "ohlcv", ["symbol"], unique=False)
    op.create_index(op.f("ix_ohlcv_timestamp"), "ohlcv", ["timestamp"], unique=False)
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("exchange_order_id", sa.String(length=64), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("exchange", sa.String(length=30), nullable=False),
        sa.Column("side", sa.Enum("buy", "sell", name="order_side"), nullable=False),
        sa.Column("order_type", sa.Enum("market", "limit", name="order_type"), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "open",
                "partially_filled",
                "filled",
                "cancelled",
                "rejected",
                name="order_status",
            ),
            nullable=False,
        ),
        sa.Column("requested_amount", sa.Float(), nullable=False),
        sa.Column("filled_amount", sa.Float(), nullable=False),
        sa.Column("requested_price", sa.Float(), nullable=True),
        sa.Column("average_fill_price", sa.Float(), nullable=True),
        sa.Column("stop_loss_price", sa.Float(), nullable=True),
        sa.Column("take_profit_price", sa.Float(), nullable=True),
        sa.Column("total_fee", sa.Float(), nullable=False),
        sa.Column("strategy_name", sa.String(length=50), nullable=False),
        sa.Column("signal_confidence", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("raw_exchange_response", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_orders_exchange_order_id"), "orders", ["exchange_order_id"], unique=True
    )
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_index(op.f("ix_orders_symbol"), "orders", ["symbol"], unique=False)
    op.create_table(
        "pnl_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("total_balance_quote", sa.Float(), nullable=False),
        sa.Column("unrealized_pnl", sa.Float(), nullable=False),
        sa.Column("realized_pnl", sa.Float(), nullable=False),
        sa.Column("total_fees", sa.Float(), nullable=False),
        sa.Column("num_open_positions", sa.Integer(), nullable=False),
        sa.Column("drawdown_pct", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pnl_snapshots_timestamp"), "pnl_snapshots", ["timestamp"], unique=False
    )
    op.create_table(
        "positions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("exchange", sa.String(length=30), nullable=False),
        sa.Column("side", sa.String(length=5), nullable=False),
        sa.Column("entry_price", sa.Float(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("stop_loss_price", sa.Float(), nullable=True),
        sa.Column("take_profit_price", sa.Float(), nullable=True),
        sa.Column("strategy_name", sa.String(length=50), nullable=False),
        sa.Column(
            "opened_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("exit_price", sa.Float(), nullable=True),
        sa.Column("realized_pnl", sa.Float(), nullable=True),
        sa.Column("is_open", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_positions_is_open"), "positions", ["is_open"], unique=False)
    op.create_index(op.f("ix_positions_symbol"), "positions", ["symbol"], unique=False)
    op.create_table(
        "tickers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("exchange", sa.String(length=30), nullable=False),
        sa.Column("bid", sa.Float(), nullable=False),
        sa.Column("ask", sa.Float(), nullable=False),
        sa.Column("last", sa.Float(), nullable=False),
        sa.Column("volume_24h", sa.Float(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tickers_exchange"), "tickers", ["exchange"], unique=False)
    op.create_index(op.f("ix_tickers_symbol"), "tickers", ["symbol"], unique=False)
    op.create_index(op.f("ix_tickers_timestamp"), "tickers", ["timestamp"], unique=False)
    op.create_table(
        "trade_signals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("exchange", sa.String(length=30), nullable=False),
        sa.Column(
            "signal_type", sa.Enum("buy", "sell", "hold", name="signal_type"), nullable=False
        ),
        sa.Column("strength", sa.String(length=10), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("strategy_name", sa.String(length=50), nullable=False),
        sa.Column("entry_price", sa.Float(), nullable=False),
        sa.Column("stop_loss_price", sa.Float(), nullable=True),
        sa.Column("take_profit_price", sa.Float(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("risk_verdict", sa.String(length=20), nullable=True),
        sa.Column(
            "timestamp",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trade_signals_symbol"), "trade_signals", ["symbol"], unique=False)
    op.create_index(
        op.f("ix_trade_signals_timestamp"), "trade_signals", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trade_signals_timestamp"), table_name="trade_signals")
    op.drop_index(op.f("ix_trade_signals_symbol"), table_name="trade_signals")
    op.drop_table("trade_signals")
    op.drop_index(op.f("ix_tickers_timestamp"), table_name="tickers")
    op.drop_index(op.f("ix_tickers_symbol"), table_name="tickers")
    op.drop_index(op.f("ix_tickers_exchange"), table_name="tickers")
    op.drop_table("tickers")
    op.drop_index(op.f("ix_positions_symbol"), table_name="positions")
    op.drop_index(op.f("ix_positions_is_open"), table_name="positions")
    op.drop_table("positions")
    op.drop_index(op.f("ix_pnl_snapshots_timestamp"), table_name="pnl_snapshots")
    op.drop_table("pnl_snapshots")
    op.drop_index(op.f("ix_orders_symbol"), table_name="orders")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_exchange_order_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_ohlcv_timestamp"), table_name="ohlcv")
    op.drop_index(op.f("ix_ohlcv_symbol"), table_name="ohlcv")
    op.drop_table("ohlcv")
    # ### end Alembic commands ###
