"""add_failed_orders_and_portfolio_snapshots

Revision ID: d47f90acdc5b
Revises: a1b2c3d4e5f6
Create Date: 2026-03-04 12:26:00.178061
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd47f90acdc5b'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=30), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('order_type', sa.String(length=6), nullable=False),
    sa.Column('requested_amount', sa.Float(), nullable=False),
    sa.Column('requested_price', sa.Float(), nullable=True),
    sa.Column('strategy_name', sa.String(length=50), nullable=False),
    sa.Column('error_reason', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_orders_resolved'), 'failed_orders', ['resolved'], unique=False)
    op.create_index(op.f('ix_failed_orders_symbol'), 'failed_orders', ['symbol'], unique=False)
    op.create_index(op.f('ix_failed_orders_timestamp'), 'failed_orders', ['timestamp'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('balance_quote', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('total_fees', sa.Float(), nullable=False),
    sa.Column('num_positions', sa.Integer(), nullable=False),
    sa.Column('positions_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_snapshots_timestamp'), 'portfolio_snapshots', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_snapshots_timestamp'), table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_index(op.f('ix_failed_orders_timestamp'), table_name='failed_orders')
    op.drop_index(op.f('ix_failed_orders_symbol'), table_name='failed_orders')
    op.drop_index(op.f('ix_failed_orders_resolved'), table_name='failed_orders')
    op.drop_table('failed_orders')
    # ### end Alembic commands ###
