"""add_cycle_history

Revision ID: fd3e40da0c31
Revises: d47f90acdc5b
Create Date: 2026-03-04 16:07:56.274447
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd3e40da0c31'
down_revision: Union[str, None] = 'd47f90acdc5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycle_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('num_signals', sa.Integer(), nullable=False),
    sa.Column('num_orders_placed', sa.Integer(), nullable=False),
    sa.Column('num_orders_filled', sa.Integer(), nullable=False),
    sa.Column('num_orders_cancelled', sa.Integer(), nullable=False),
    sa.Column('num_orders_failed', sa.Integer(), nullable=False),
    sa.Column('portfolio_balance', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('circuit_breaker_tripped', sa.Boolean(), nullable=False),
    sa.Column('errors_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cycle_history_cycle_number', 'cycle_history', ['cycle_number'], unique=True)
    op.create_index('ix_cycle_history_timestamp', 'cycle_history', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cycle_history_timestamp', table_name='cycle_history')
    op.drop_index('ix_cycle_history_cycle_number', table_name='cycle_history')
    op.drop_table('cycle_history')
    # ### end Alembic commands ###
